### ISSUE TITLE
Python 2.6 test failures in Travis

### ISSUE THREAD

**Issue by Scotchester** [cfpb/collab#70]
When [this commit](https://github.com/cfpb/collab/pull/57/commits/0859b16d54c2d55e4c35b2e05d293dbf3592f8e4) was added to [this PR](https://github.com/cfpb/collab/pull/57), Travis started [erroring while running tests on Python 2.6](https://travis-ci.org/cfpb/collab/jobs/194960540) for reasons that are unclear.

Observations:
- Running the tests locally with the Three Puppeteers Vagrant setup does not produce any of these errors, nor does running the tests directly on our Intranet test server.
- Travis is running Python 2.6.9; both the Three Puppeteers dev environment and the Intranet test server are running Python 2.6.6.
- `ImportError: cannot import name OrderedDict` is reported eight times.
- The final summary reports: `7119 tests, 0 failures, **6 errors** in 3.8s` (emphasis added)
- The commit in question doesn't appear to do anything that isn't supported in Python 2.6.

**Comment by willbarton** [comment]
The use of `OrderedDict` is. It was added in Python 2.7.

**Comment by Scotchester** [comment]
@willbarton So why do the tests pass locally/on the server?

**Comment by Scotchester** [comment]
And, if you review the PR (#57), why did Travis not start failing on the commit that introduced `OrderedDict`, https://github.com/cfpb/collab/pull/57/commits/af230bf0a23364dd8c30793de4d740c151c5af73? It started failing one commit later, https://github.com/cfpb/collab/pull/57/commits/0859b16d54c2d55e4c35b2e05d293dbf3592f8e4).

**Comment by willbarton** [comment]
In the words of Knuth:

> I have only proved it correct, not tried it.

`from collections import OrderedDict` should always fail on python 2.6.x.

```python
Python 2.6.9 (unknown, Jul 14 2015, 19:46:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import OrderedDict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name OrderedDict
```

There is [an `ordreddict` package on pypi that can be used for 2.4-2.6](https://pypi.python.org/pypi/ordereddict), but then the import would look like:

```python
try:
    from collections import OrderedDict
except ImportError:
    from ordereddict import OrderedDict
```

**Comment by Scotchester** [comment]
You're still not helping me understand _why_ it happened when it did, and why the software works and tests pass on our actual servers.

**Comment by Scotchester** [comment]
@willbarton Didn't mean for that to sound snippy, I just want to know! :)

**Comment by willbarton** [comment]
Can you import `OrderedDict` from `collections` in the environment where they successfully pass and run?

**Comment by Scotchester** [comment]
I sure can.

```python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import OrderedDict
>>> 
```

**Comment by willbarton** [comment]
So, after some digging with @Scotchester, we've found that Red Hat apparently modifies the Python 2.6.6 standard library `collections` to include `OrderedDict`.

Comparing the Python 2.6.6 source code with the `/usr/lib64/python2.6/collections.py` file as well as with the contents [of the python-libs-2.6.6 RPM](
http://mirror.centos.org/centos/6/os/x86_64/Packages/python-libs-2.6.6-66.el6_8.x86_64.rpm) shows they do not match. Red Hat has broken the promise of the **standard** library.

![flames](http://prcoparenting.com/wp-content/uploads/2015/11/Flames1.gif)

**Comment by willbarton** [comment]
[This comment in Red Hat's Bugzilla appears to confirm](https://bugzilla.redhat.com/show_bug.cgi?id=1199997#c0), but I can't access the bug it links to.
